---
#
# Create and configure Linux accounts for administrators
#
- name: Add administrators
  tags:
    - admins
  #
  # Generate password with:
  #
  #   openssl passwd -salt <salt> -1 <plaintext>
  #
  #
  user: name={{ item }} password=[GENERATED PASSWORD] shell=/bin/bash update_password=on_create
  with_items: "{{ admins }}"
  register: admin_added

- name: Add SSH keys
  authorized_key:
    user={{ item }}
    exclusive=yes
    key="{{ lookup('file', 'keys/' + item + '.pub')}}"
  with_items: "{{ admins }}"

- name: Add to sudoers
  lineinfile:
    "dest=/etc/sudoers
    regexp='^{{ item }} ALL'
    line='{{ item }} ALL=(ALL) PASSWD: ALL'
    state=present"
  with_items: "{{ admins }}"
...
