---
# Create Droplets
- name: "Read SSH vars"
  include_vars:
    file: ssh_keys.json
    name: ssh_keys

- name: "Create droplets"
  tags: 
    - create_droplet
  digital_ocean:
    backups_enabled: "{{ item.backups_enabled | d('no') }}"
    command: droplet
    image_id: "{{ item.image_id | d('ubuntu-16-04-x64') }}"
    name: "{{ item.name }}"
    private_networking: "{{ item.private_networking | d('no') }}"
    region_id: "{{ item.region_id | d('fra1') }}"
    size_id: "{{ item.size_id | d('512mb') }}"
    ssh_key_ids: "{{ ssh_keys | json_query('results[*].ssh_key') | selectattr('name', 'equalto', item.ssh_key_name) | map(attribute='id') | list }}" 
    state: present
    unique_name: yes
    user_data: "{{ lookup('template', 'user-data.j2') | trim }}"
    virtio: "{{ item.virtio | d('yes') }}"
    wait: "{{ item.wait | d('yes') }}"
    wait_timeout: "{{ item.wait_timeout | d(600) }}"
  with_items: 
    - "{{ do_droplets1 }}"
  register: result_droplets 

- name: "Extract droplet information"
  tags:
    - create_droplet
  set_fact: do_droplets_with_ip="{{ result_droplets | json_query(droplet_query) }}"
  vars:
    droplet_query: "results[*].{ ip: droplet.ip_address, port: item.port, name: droplet.name, user: item.user, ssh_key_name: item.ssh_key_name }"
  changed_when: no

- name: "Wait for ssh port to become available"
  tags:
    - create_droplet
  local_action: "wait_for port={{ item.port }} host={{ item.ip }}"
  with_items: "{{ do_droplets_with_ip }}"

- name: "Add digitalocean group to inventory"
  tags:
    - create_droplet	  
  lineinfile:
    dest: "{{ do_inventory_file }}"
    line: "[digitalocean]"
  when: do_inventory_file is defined and do_inventory_file

- name: "Add droplets to inventory"
  tags:
    - create_droplet
  lineinfile:
    dest: "{{ do_inventory_file }}"
    regexp: "^{{ item.name }} ansible_host=.*"
    line: "{{ item.name }} ansible_host={{ item.ip }}"
    insertafter: "\\[digitalocean\\]"
  with_items: "{{ do_droplets_with_ip }}"
  when: do_inventory_file is defined and do_inventory_file
...
